### ISSUE TITLE
Error trying to start

### ISSUE THREAD

**Issue by fralippolippi** [newscorpaus/consigliere#16]
From the npm-debug.log

9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid consigliere@1.0.0
11 verbose cwd /home/ec2-user/consigliere
12 error Linux 4.4.30-32.54.amzn1.x86_64
13 error argv "/home/ec2-user/.nvm/versions/node/v4.1.0/bin/node" "/home/ec2-user/.nvm/versions/node/v4.1.0/bin/npm" "start"
14 error node v4.1.0
15 error npm  v2.14.3
16 error code ELIFECYCLE
17 error consigliere@1.0.0 start: `export NODE_CONFIG_DIR='./src/config' ; node_modules/forever/bin/forever start -a -l /var/log/consigliere/forever.log -o /var/log/consigliere/forever.out.log -e /var/log/consigliere/forever.err.log src/index.js`
17 error Exit status 1
18 error Failed at the consigliere@1.0.0 start script 'export NODE_CONFIG_DIR='./src/config' ; node_modules/forever/bin/forever start -a -l /var/log/consigliere/forever.log -o /var/log/consigliere/forever.out.log -e /var/log/consigliere/forever.err.log src/index.js'.
18 error This is most likely a problem with the consigliere package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     export NODE_CONFIG_DIR='./src/config' ; node_modules/forever/bin/forever start -a -l /var/log/consigliere/forever.log -o /var/log/consigliere/forever.out.log -e /var/log/consigliere/forever.err.log src/index.js
18 error You can get their info via:
18 error     npm owner ls consigliere
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by danielkoo** [comment]
Hi @fralippolippi 
Apologies for the delay - for some reason I don't think I saw a notification :(

It looks like something went wrong running that set of commands (essentially exporting an environment variable and then running Forever).
Is there anything else that was shown on the output that might give more info?
Does the /var/log/consigliere dir exist, and is it writeable by the user?
