### ISSUE TITLE
Internal implementation error

### ISSUE THREAD

**Issue by dre2004** [newscorpaus/consigliere#30]
Hello team,

I've been running this app for several weeks now but it seems in the last couple of days it's stopped working without any changes made on my end.

I'm getting the following error (identifiable info removed)

```
2017-11-21T05:14:20.944Z - info: Lib/StatFetcher : GET /api/category/cost_optimizing | Successfully got summary category for all accounts
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'not_available' of undefined
    at /xxx/consigliere/src/lib/statfetcher.js:258:80
    at Array.forEach (native)
    at /home/xxx/consigliere/src/lib/statfetcher.js:256:27
    at Array.forEach (native)
    at Command.<anonymous> (/xxx/consigliere/src/lib/statfetcher.js:255:31)
    at bound (domain.js:287:14)
    at Command.runBound (domain.js:300:12)
    at normal_reply (/xxx/consigliere/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/xxx/consigliere/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.Parser.returnReply (/xxx/consigliere/node_modules/redis/index.js:192:18)
```

When I take a look at redis I see the following output from a result

```
127.0.0.1:6379> get "548877764401_result_bW7HH0l7J9"
"{\"result\":{\"checkId\":\"bW7HH0l7J9\",\"status\":\"not_available\"}}"
```

In the summaries records I'm seeing 0 values for all the key pairs as well.  Has something potentially changed on the AWS side that's broken Consigliere?

**Comment by rdehavenl** [comment]
We are experiencing this as well... Perhaps a change in the API results?

**Comment by dre2004** [comment]
@rdehavenl how did you force a refresh of the information in the AWS console?

**Comment by rdehavenl** [comment]
Sorry, this worked for a few days, then fell out again.  I don't know how best to fix this at the moment
